# Docker Compose configuration for UWCS Academy

# Include judge0
include:
  - services/judge0-v1.13.1/docker-compose.yml

services:

  # Frontend (/academy-webapp)
  webapp:
    build: ./academy-webapp
    ports:
      # - "5173:4173"
      - "5173:5173"
    env_file: ".env"
    depends_on:
      - db
  
  # Microservices (/service) 
  update_content:
    build: ./services/update_content
    volumes:
      - ./content:/app/content:rw
    env_file: ".env"
    depends_on:
      - db
    stop_grace_period: "1s"

  # Static File Server
  file_server:
    image: nginx:1.29.0
    volumes:
      - ./content:/usr/share/nginx/html

  # Database
  db:
    image: "postgres:17.5"
    restart: always
    env_file: ".env"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  pgdata: