services:
  webapp:
    build: ./academy-webapp
    ports:
      - "5173:4173"
    env_file: "config/.env"
    depends_on:
      - db
    volumes:
      - ./config:/app/config
  update_content:
    build: ./services/update_content
    volumes:
      - ./content:/app/content:ro
    env_file: "config/.env"
    depends_on:
      - db
    stop_grace_period: "5s"

  db:
    image: "postgres:17.5"
    restart: always
    env_file: "config/.env"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  pgdata: