services:
  webapp:
    build: ./academy-webapp
    ports:
      - "5173:4173"
    env_file: 
      - "config/webapp.env"
      - "config/db.env"
    depends_on:
      - db
  db:
    image: "postgres:17.5"
    restart: always
    env_file: "config/db.env"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  pgdata: